### PR TITLE
Update the atom.xml format

### PR DESCRIPTION
**Pull request by jinhojang6**
**Updates**

- Add `author` to  atom.xml. For example,
```
<author>
        <name>eric_mastro</name>
</author>
```

- Use text for "summary" which was an html before.
```
from
<summary type="html"> <p><img src="/assets/images/mythx_dashboard.png" alt="Embark dashboard with MythX"></p> <h2 id="How-MythX-works"><a href="#How-MythX-works" </summary>

to 
<summary>Analyse Smart Contract security throughout the development lifecycle using the Embark MythX plugin.</summary>
```

**XML format examples**

- Before: https://blog.embarklabs.io/atom.xml

- After: https://drive.google.com/file/d/1YC3Ts_AhBzCYhACIEQn5IUxBRNvzcn5N/view?usp=sharing

The summary and author information will be used at https://tutorials.statusnetwork.com/ (like Nimbus)

**Test**

1. Run `hexo generate`

2. Check out `public/atom.xml`

### CODE REVIEW

**Review by jakubgs — APPROVED** [review]
You added `hexo-generator-seo-friendly-sitemap` but did not remove `hexo-generator-sitemap` so you didn't see it work. Which is why I guess you did it the `atom.xml` way. That's fine, but if you're not using `hexo-generator-seo-friendly-sitemap` you should remove it.

I'll push a commit that fixes that, adds some `scripts` to `package.json`, and replaces `hexo-renderer-sass` - which uses and __ancient__ version of `node-sass` - with `hexo-render-sass` which uses much more recent `4.13.1`. See if this is fine with you. Also reverts the `db.json` changes.

**Comment by jinhojang6** [comment]
Nice, thanks @jakubgs

**Comment by jakubgs** [comment]
Actually, `db.json` file is something `hexo serve` generates to improve performance, it should have __never__ been commited to the repo in the first place. I'll update `.gitignore` too.

**Comment by jinhojang6** [comment]
@iurimatias Can we merge this PR?

**Review by iurimatias — APPROVED** [review]

**Pull request merged**
